[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
js_watcher = { path = "../js_watcher", features = ["without-napi"] }
clap = { version = "3.1.8", features = ["derive"] }
owo-colors = "3.3.0"
ctrlc = "3.2.1"
serde_json = "1.0.79"
shellwords = "1.1.0"