[package]
name = "bin"
version = "0.1.0"
edition = "2021"


[dependencies]
js_watcher = { path = "../js_watcher", features = ["without-napi"] }
path-absolutize = "3.0.12"


[profile.release]
lto = true
codegen-units = 1

[profile.test]
lto = true
codegen-units = 1